build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build with dotnet
        run: dotnet build Busticket/Busticket.csproj --configuration Release

      - name: dotnet publish
        # Publicamos en una carpeta local llamada 'myapp'
        run: dotnet publish Busticket/Busticket.csproj -c Release -o ./myapp --no-self-contained

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./myapp

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./to_deploy # Descarga en una subcarpeta

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AEC5DB626120413DB5695ECB97A38CD4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7C9B1F4CF7414F499A7DD63879672F9C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B2E7921EDDFE470ABEA23778262CEF6E }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'BusTickets'
          package: ./to_deploy # Azure tomará el contenido de esta carpeta
