name: Build and deploy ASP.Net Core app to Azure Web App - BusTickets

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build with dotnet
        run: dotnet build Busticket/Busticket.csproj --configuration Release

      - name: dotnet publish
        # Publicamos en una carpeta limpia llamada 'publish'
        run: dotnet publish Busticket/Busticket.csproj -c Release -o ./publish --no-self-contained

      - name: List files after publish
        run: dir ./publish /s

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: net-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: net-app
          path: ./artifact

      - name: List files to deploy
        run: dir ./artifact /s

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'BusTickets'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          # Apuntamos a la carpeta correcta dentro del artifact
          package: ./artifact
