name: Build and deploy ASP.Net Core app to Azure Web App - BusTickets

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Busticket/Busticket.csproj

      - name: Build with dotnet
        run: dotnet build Busticket/Busticket.csproj --configuration Release --no-restore

      - name: dotnet publish
        # Usamos --no-self-contained para que el archivo sea mucho más pequeño
        run: dotnet publish Busticket/Busticket.csproj -c Release -o ./out --no-self-contained

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: net-app
          path: ./out

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: net-app
          path: ./publish-folder

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'BusTickets'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          # Al estar WEBSITE_RUN_FROM_PACKAGE=1, Azure recibirá esto y lo tratará como el paquete de ejecución
          package: ./publish-folder
